name: Frontend CI

on:
  pull_request:
    paths:
      - "frontend/**"

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install frontend dependencies
        run: bun install

      - name: Run OX Lint
        run: bun lint:oxlint

      - name: Build frontend
        run: bun run build
